export const questions = {
    'class':9,
    'Musical intelligence': [
        "How often do you notice and remember melodies or tunes you hear throughout the day?",
        "When listening to a song, how easily can you identify changes in rhythm or tempo?",
        "How frequently do you experiment with creating your own music or beats using either an instrument or a digital platform?",
        "When listening to a piece of music, how easily can you differentiate between various instruments or sounds?",
        "How confident are you in recognizing different musical genres (such as classical, jazz, pop, etc.) based on a short sample of music?",
        "How often do you find yourself tapping your feet, drumming your fingers, or moving your body in sync with the music you hear?",
        "When learning a new song or melody, how easily can you replicate it by ear, either through singing, humming, or playing an instrument?",
        "How frequently do you feel emotionally moved or affected by the music you listen to?",
        "When exposed to a repetitive rhythm, how easy is it for you to maintain or repeat the rhythm through clapping, tapping, or vocalizing?",
        "How often do you actively seek to listen to music as a way to focus, relax, or motivate yourself?"
    ],
    'Linguistics intelligence': [
        "How often do you find yourself engaging in creative writing (e.g., stories, poems, essays) in your free time?",
        "When learning new vocabulary, how easily can you remember and use new words in conversation or writing?",
        "How often do you notice the structure and grammar of sentences when reading or listening to someone speak?",
        "How easily can you tell a story, explain a concept, or describe an event in a clear and engaging way?",
        "When faced with a complex text, how confidently can you comprehend and interpret the underlying meaning or message?",
        "How often do you enjoy engaging in wordplay, such as puns, rhymes, or creating new words?",
        "How easily can you learn and understand the rules of a new language?",
        "When reading or listening to a debate, how well can you follow the argument and identify the strengths or weaknesses of each side?",
        "How often do you find yourself using descriptive or vivid language in conversations or writing?",
        "How frequently do you use writing or speaking to clarify your thoughts or express your emotions?"
    ],
    'Spatial Intelligence': [
        "How easily can you visualize how an object would look if rotated or viewed from a different angle?",
        "When looking at a map or set of directions, how well can you understand and follow the route in your mind before moving?",
        "How often do you enjoy engaging in activities that involve design or visualization, such as drawing, building models, or creating digital designs?",
        "When assembling furniture or following step-by-step instructions for building something, how easily can you picture each step before doing it?",
        "How confidently can you mentally manipulate shapes and figures when solving puzzles such as jigsaw puzzles, tangrams, or 3D puzzles?",
        "When given a complex diagram or technical drawing (e.g., architectural blueprints or engineering schematics), how well can you understand and interpret it?",
        "How often do you find yourself using visual imagery to solve problems, such as imagining how different pieces fit together or visualizing outcomes before acting?",
        "When given a set of geometric shapes, how easily can you recognize patterns or relationships between them?",
        "When watching a movie or reading a description of a scene, how vividly can you imagine the setting in your mind?",
        "How often do you mentally rearrange furniture or objects in a room, either to improve the layout or to visualize how a space could look?"
    ],
    'Intrapersonal intelligence': [
        "How often do you take time to reflect on your emotions and the reasons behind them?",
        "When faced with a difficult decision, how easily can you identify your personal values or goals that will guide your choice?",
        "How well do you understand your strengths and weaknesses when it comes to academic, social, or personal challenges?",
        "How often do you set personal goals and track your progress in achieving them?",
        "When you're feeling stressed or overwhelmed, how effectively can you manage your emotions and return to a calm state?",
        "How frequently do you engage in activities or practices (e.g., journaling, meditation, or self-reflection) that help you better understand yourself?",
        "When making plans for the future, how well can you foresee potential obstacles and your personal reactions to them?",
        "How often do you find yourself adjusting your behavior or thoughts after learning something new about yourself?",
        "When facing failure or setbacks, how well do you understand your emotional reactions and use them to improve yourself?",
        "How well do you recognize the factors that motivate you, and how effectively do you use this knowledge to stay focused on your goals?"
    ],
    'Interpersonal intelligence': [
        "How easily can you understand how someone is feeling just by observing their facial expressions, tone of voice, or body language?",
        "When working in a group or team, how effectively do you communicate your ideas and listen to the perspectives of others?",
        "When someone is upset or going through a difficult time, how well can you offer support or help them work through their emotions?",
        "How comfortable are you in leading group discussions or projects, and how well do you ensure that everyone contributes?",
        "How often do you find yourself able to resolve conflicts between others or mediate disputes in a calm and fair manner?",
        "When working with people from different backgrounds or with different perspectives, how well can you adapt your communication style to suit them?",
        "How often do you find yourself helping to build a positive atmosphere in a group by encouraging others or resolving tension?",
        "How well do you understand what motivates the people around you, such as classmates, friends, or family members?",
        "When someone disagrees with your opinion, how effectively can you handle the disagreement without becoming defensive or upset?",
        "When you meet someone new, how easily can you build rapport and establish a connection with them?"
    ],
    'Logical-Mathematical intelligence': [
        "How easily can you recognize patterns or trends in numbers, data, or events?",
        "When presented with a complex problem, how efficiently do you break it down into smaller, more manageable steps?",
        "How well can you use logic to assess different options and determine the best course of action in a given situation?",
        "How often do you use mathematical concepts or reasoning in everyday situations, such as calculating costs, measuring, or solving puzzles?",
        "When faced with a word problem or math problem, how effectively can you identify the key information needed to solve it?",
        "How well do you understand abstract concepts like probability, ratios, or algebraic equations?",
        "How often do you challenge yourself with puzzles, brain teasers, or logic games that require you to think critically?",
        "How easily can you visualize and manipulate shapes, objects, or numbers in your mind when solving problems?",
        "When you're faced with a scientific problem or question, how well can you hypothesize possible outcomes and test your assumptions?",
        "How comfortable are you when working with numbers, formulas, or calculations in subjects like math, physics, or economics?"
    ],
    'Naturalist intelligence': [
        "How well can you identify different plants, animals, or insects in your surroundings without the need for external help?",
        "How often do you spend time outdoors observing nature, such as walking through parks, forests, or beaches?",
        "When you see changes in the environment, such as seasonal changes or changes in the weather, how easily do you notice and understand them?",
        "How well can you recognize different ecosystems (e.g., forest, desert, wetlands) and understand the interactions between living and non-living things within them?",
        "When learning about environmental issues (such as climate change or pollution), how interested are you in finding solutions or taking action?",
        "How easily do you notice the differences in plants or animals, such as their size, shape, color, or behavior?",
        "When you visit different natural environments, such as mountains, rivers, or forests, how well can you identify the natural features unique to each environment?",
        "How familiar are you with using natural materials or substances (like plants, herbs, or minerals) for practical purposes, such as in cooking, medicine, or crafting?",
        "How well can you describe the impact of human activities, such as deforestation or urbanization, on the environment and the species within it?",
        "When you hear about endangered species or ecosystems, how motivated are you to learn more about their importance and what can be done to protect them?"
    ],
    'Bodily-Kinesthetic intelligence': [
        "How easily can you learn physical activities, such as new sports, dance routines, or exercises, by observing or practicing?",
        "How well can you control your body movements when performing tasks like balancing, jumping, or maneuvering through obstacles?",
        "When performing activities that require fine motor skills, such as drawing, sewing, or assembling objects, how accurate and precise are you?",
        "How often do you find yourself using hand gestures, body movements, or facial expressions to explain something or express your thoughts?",
        "When working on a physical project or activity, such as building, crafting, or sports, how naturally can you manipulate objects to achieve your desired result?",
        "How comfortable are you with tasks that require physical endurance, strength, or flexibility, such as sports, yoga, or fitness activities?",
        "How well can you coordinate multiple body parts when performing complex tasks, such as dancing, playing an instrument, or doing gymnastics?",
        "When participating in team sports or physical group activities, how effectively do you cooperate and synchronize your movements with others?",
        "How easily can you recall and replicate specific body movements or techniques after seeing them demonstrated once or twice?",
        "How often do you prefer learning by doing—actively engaging in hands-on tasks or activities rather than reading or listening?"
    ],
    'Moral intelligence': [
        "How often do you reflect on whether your actions are fair to others?",
        "When making decisions, how much importance do you place on the ethical implications of your choice?",
        "How often do you stand up for someone who is being treated unfairly, even if it might be difficult for you?",
        "When you're involved in a disagreement, how much do you try to understand the perspective of the other person?",
        "How frequently do you think about the long-term consequences of your actions on others or society?",
        "How well can you identify situations where something is unjust or unethical, even if it doesn't directly affect you?",
        "How often do you follow through on promises or commitments, even when it's challenging?",
        "When you witness someone doing something wrong, how comfortable are you in addressing the issue or reporting it?",
        "How often do you consider the moral impact of your words or actions before speaking or acting?",
        "When facing a moral dilemma, how easily can you balance your personal interests with the greater good?"
    ]
}
